### PR TITLE
math: TDD for evaluate functions (missing trigonometric and constants)

### PR DESCRIPTION
**Pull request by TheRetikGM**
I have written some basic TDD tests for the math library. There are still some missing (such as testing full expressions). I will add those soon.

Some tests I didn't know how to write, because it seems the math lib API doesn't provide the methods yet. That includes:
- changing the working units for trigonometric functions and as I don't know which ones they will use implicitly I have just marked the tests with `todo!()` macro for now
- Generating the pseudo-random numbers. I don't know if this should be a method in the Calculator struct or not, so this tests is the only one, which isn't prefixed with `evaluate_`

I would add the rest of the tests after the API edit. Also I have marked the lines of code, which I am not too sure about with `// NOTE` comments.

### CODE REVIEW

**Comment by tmokenc** [comment]
My bad, I'm currently working on the `Number` function and its API looks completely different from the current version on main branch.

Since the specification just need the number to represents in binary/octal/decimal/hexadecimal so I split them into different functions, additionally add the precision parameter.
Its API looks like this 
```rust
pub fn to_string(&self, precision: u8) -> String;
pub fn to_string_binary(&self, precision: u8) -> String;
pub fn to_string_octal(&self, precision: u8) -> String;
pub fn to_string_hex(&self, precision: u8) -> String;
```

You can find more about it [here](https://github.com/tmokenc/IVS-projekt-2/blob/number/src/math/src/number.rs).
I don't know if it's a good design or not, please give me your opinion about this.

Also a note that you can put test files into `test/` folder (not `src/`) and do not need to include it into the lib, `cargo test` will find and execute it automatically, and it's the prefered way of intergration testing in Rust,

**Comment by tmokenc** [comment]
Also instead of writing `.unwrap`, you can use the [`?` operator](https://doc.rust-lang.org/rust-by-example/std/result/question_mark.html).
The test function will look like this
```rust
#[test]
function foo() -> math::Result<()> {
    assert_eq!(evaluate("1 + 2")?.to_string(6), "3");
    assert_eq!(evaluate("0.1 + 0.2")?.to_string(6), "0.3");
    Ok(())
}
```

**Comment by TheRetikGM** [comment]
I see. Then I will wait until you push the new API and create the tests for it after.

As for the `to_string` methods, maybe it could be implemented something like this
```rust
pub enum Radix {
    dec,
    bin,
    oct,
    hex
}
// ...
pub fn to_string(&self, precision: u8, radix: Radix) -> String;
```
This would allow the external code to look something like this:
```rust
let radix = get_selected_radix();
let result = math::evaluate("1 + 1")?.to_string(6, radix);
show_result(result);
```
However this could also be implemented with a  wrapper function, so in the end it doesn't matter much.

**Comment by tmokenc** [comment]
That looks waaaaay cleaner.
I have updated its API and any further discussion on the `Number` API will [be here](https://github.com/FIT-IVS-segmentation-fault-core-dumped/IVS-projekt-2/pull/5)

**Pull request closed without merging**
