### PR TITLE
Add `Calculator` API

### PR DESCRIPTION
**Pull request by tmokenc**
The `Calculator` struct API, I would say that it is fully working API, the only thing left to do is to implement an `Engine`

# Calculator
```rs
impl Calculator {
    fn new() -> Self;
    fn add_constant(&mut self, name: &str, value: Number) -> bool;
    fn get_constant(&self, name: &str) -> Option<Number>;
    fn remove_constant(&mut self, name: &str) -> Option<Number>;
    fn constants(&self) -> impl Iterator<Item=(&str, Number)>;
    fn evaluate(&mut self, expression: &str) -> math::Result<Number>;
}

fn evaluate(expression: &str) -> Result<Number>;
```

- Custom constant can be added/updated via `add_constant` function, and its name is case-insensitive
- If `evaluation` function call succeeds, it will put the result as `ANS` into the constant list automatically, so the next expression with `ANS()` will give the value of the last expression

The `evaluation` function outside of the `Calculator` struct is simply shorthand for `Calculator::new().evaluate(expression)`

### CODE REVIEW

**Comment by tmokenc** [comment]
This is just my ideal API, do you want to to add or edit something about this? @TheRetikGM @Blazeo7

**Comment by TheRetikGM** [comment]
Looks good, however what about deleting and getting values of constants?

**Comment by tmokenc** [comment]
Oh yeah sure! That didn't cross my mind.
Updated

**Comment by tmokenc** [comment]
The `evaluate` function is usable now. Did not pass all the test but I will save them for other PR

**Pull request merged**
